apiVersion: v1
kind: Secret
metadata:
  name: prometheus-federation-scrape-config
  namespace: central-monitoring-system
stringData:
  prometheus-federation.yaml: |
    - job_name: "federation"
      metrics_path: "/federate"
      scheme: https
      metric_relabel_configs:
        - source_labels:
            - instance
          regex: prometheus\.([a-z\-]+)\.[0-9\.]+\.sslip\.ip:443
          target_label: cluster
        - source_labels:
            - exported_instance
          target_label: instance    
        - source_labels:
            - exported_job
          target_label: job    
        - action: labeldrop
          regex: exported_.*         
      params:
        "match[]": [ '{__name__=~".+"}' ]
      basic_auth:
        username: foo
        password: bar
      static_configs:
        - targets: 
          - "prometheus.central.3.72.51.158.sslip.io:443"
          - "prometheus.fleet01.3.70.191.233.sslip.io:443"
          - "prometheus.fleet02.18.197.142.118.sslip.io:443"
          - "prometheus.fleet03.18.156.137.178.sslip.io:443"