apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  namespace: shop
spec:
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        args:
          - /etc/redis/redis.conf
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-data
        - mountPath: /etc/redis
          name: redis-conf
        resources:
          limits:
            memory: 256Mi
            cpu: 125m
          requests:
            cpu: 70m
            memory: 200Mi
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        ports:
        - containerPort: 9121
          name: metrics
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 9121
      volumes:
      - name: redis-data
        emptyDir: {}
      - name: redis-conf
        configMap:
          name: redis-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
data:
  redis.conf: |
    maxmemory 20mb
