apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: cattle-monitoring-system
type: kubernetes.io/basic-auth
data:
  username: dXNlcg== # username: user
  password: cGFzc3dvcmQ= # password: password
